### PR TITLE
fix(android,fileIO) : remove file check that prevent file reading on android

### LINKED ISSUE #788: Android: `log_level_config.json` not found.
I'm seeing this error in Android build after updating to latest from `3.1.0`:

```csharp
Error Unity FileNotFoundException: Config file "jar:file:///data/app/~~GlkpSHNC1KZ_kWCHd5yOKw==/*package name*-6PIJZtVpcHpmNAccpkJn_Q==/base.apk!/assets/EOS/log_level_config.json" does not exist.
```

I see the file in `StreamingAssets/EOS`, and I'm not seeing the issue in editor and PC, PS5 builds. Not sure about other platforms.

Using Unity `2021.3.35`. Is there any special setup needed for the new config file on Android?

### PR DESCRIPTION
**Pull request by arthur740212**
`File.Exist` will always return false for android files, thus this is modified.

The UNITY_EDITOR `Write` can be isolated because `Write` is only meant to happen on editor play mode.

The file check for other platforms could be omitted because they are handled in `ReadAllText` function of their respective platform.

### CODE REVIEW

File: Assets/Plugins/Source/Core/Config.cs [hunk 1]
```diff
@@ -280,22 +280,16 @@ protected virtual async Task ReadAsync()
         /// </summary>
         protected virtual void Read()
         {
-            bool configFileExists = File.Exists(FilePath);
-
-            if (configFileExists)
+            
+#if UNITY_EDITOR // This should only happen in Editor Runtime (Play Mode)
+            if (!File.Exists(FilePath))
```
Comment (paulhazen) [inline Assets/Plugins/Source/Core/Config.cs]: During runtime when not in the editor - how do Config files get read?

I think most of them utilize `ReadAsync`, but I think that's just a coincidence.

**Review by paulhazen — CHANGES_REQUESTED** [review]
My main concern is that I was fairly certain that the `Read()` function on the `Config` class _is_ utilized within contexts where the editor is not running.

Regardless of that factor - changes made to `Read()` should also be replicated in `ReadAsync()`.

Is it possible that a better solution would be to never use `File.Exists`, but instead implement a platform-aware method within `FileUtility` that can determine if a file exists on any platform (I believe only Android would need to have a unique implementation).

File: Assets/Plugins/Source/Core/Config.cs (hunk 1 above)
Comment (arthur740212) [reply Assets/Plugins/Source/Core/Config.cs]: During runtime on any platform (including editor), it does use this `Read()`
The comment here is talking about the `Write`.
I'll add a couple words to make it clear.

ReadAsync is used in editor when not in runtime (i.e. in EditorsWindows)

**Comment by arthur740212** [comment]
> My main concern is that I was fairly certain that the `Read()` function on the `Config` class _is_ utilized within contexts where the editor is not running.
> 
To be precise.
`Read()` is for Player mode (including player mode on editor).
`ReadAsync()` is for editor mode (in other words, in editor but not in player mode).

> Regardless of that factor - changes made to `Read()` should also be replicated in `ReadAsync()`.
> 
`ReadAsync()` does not need these changes because it only runs in the editor, which means File.Exist will have expected behavior.

> Is it possible that a better solution would be to never use `File.Exists`, but instead implement a platform-aware method within `FileUtility` that can determine if a file exists on any platform (I believe only Android would need to have a unique implementation).
>
We can, but in this case wouldn't need to.

**Comment by arthur740212** [comment]
Because `ReadAsync` is only called in Editor Windows (kudos for handling those). 
I am thinking if there is a way to separate the two and prevent cross usage. The easiest way is simply doing an #if UNITY_EDITOR around `ReadAsync`

**Review by andrew-hirata-playeveryware — APPROVED** [review]

File: Assets/Plugins/Source/Core/Config.cs [hunk 2]
```diff
@@ -280,22 +280,16 @@ protected virtual async Task ReadAsync()
...
-            bool configFileExists = File.Exists(FilePath);
-
-            if (configFileExists)
-            {
-                _lastReadJsonString = FileUtility.ReadAllText(FilePath);
-                JsonUtility.FromJsonOverwrite(_lastReadJsonString, this);
-            }
-            else
+            
+#if UNITY_EDITOR // This should only happen in Editor Runtime (Play Mode)
```
Comment (andrew-hirata-playeveryware) [inline Assets/Plugins/Source/Core/Config.cs]: We should leave a comment on _why_ this should only happen in editor mode.

**Review by paulhazen — APPROVED** [review]
