### PR TITLE
fix: Properly support behavior when `EOS_DISABLE` is defined.

### LINKED ISSUE #653: Error when using EOS_DISABLE define
Error when using EOS_DISABLE define:
`Library/PackageCache/com.playeveryware.eos@74682501a1/Runtime/macOS/Core/MacOSPlatformSpecifics.cs(47,43): error CS0246: The type or namespace name 'PlatformSpecifics<>' could not be found (are you missing a using directive or an assembly reference?)`

### PR DESCRIPTION
**Pull request by paulhazen**
In some circumstances (some build configurations) if the scripting define `EOS_DISABLE` has been added within the Player Settings window of the Unity project, compilation errors will result.

This PR represents changes that affect the correct implementation of that define. Along the way, missing comments were added to the `IOSBuilder` class, and some very minor formatting changes were made to increase readability.

This closes issue #653.

### CODE REVIEW

File: Assets/Plugins/iOS/Editor/IOSBuilder.cs [hunk 1]
```diff
@@ -46,14 +64,27 @@ public override void PostBuild(BuildReport report)
             string targetGUID = proj.GetUnityMainTargetGuid();
             string unityTargetGUID = proj.GetUnityFrameworkTargetGuid();
 
-            proj.SetBuildProperty(targetGUID, "ENABLE_BITCODE", "false");
-            proj.SetBuildProperty(unityTargetGUID, "ENABLE_BITCODE", "false");
+            proj.SetBuildProperty(
```
Comment (andrew-hirata-playeveryware) [inline Assets/Plugins/iOS/Editor/IOSBuilder.cs]: I'm not certain if I like this style change.

Comment (paulhazen) [reply Assets/Plugins/iOS/Editor/IOSBuilder.cs]: No problem, I reverted to the previous style of having it all on one line. I only realized in retrospect that I had not made separate commits between the style change and the actual fix. Ideally, they would be two different tasks - but decoupling them seemed like more work than it was worth. Easy to fix small preferences like this though.

**Review by andrew-hirata-playeveryware — APPROVED** [review]
