### PR TITLE
Hotfix 3.1.3

### LINKED ISSUE #620: Fail to find RTCOptions in 3.1.2 UNITY_EDITOR_OSX (3.1.1 works)
Library/PackageCache/com.playeveryware.eos@c13536130d/Runtime/Core/PlatformSpecifics.cs(91,55): error CS1061: 'Options' does not contain a definition for 'RTCOptions' and no accessible extension method 'RTCOptions' accepting a first argument of type 'Options' could be found (are you missing a using directive or an assembly reference?)

### PR DESCRIPTION
**Pull request by arthur740212**
Hotfix 3.1.3

- Mac create option fix
- plugin deployment check

### CODE REVIEW

File: Assets/Plugins/Source/Editor/Utility/BuildUtility.cs [hunk 1]
```diff
@@ -70,25 +70,39 @@ public static bool DeployedAsUPM
...
+
+            //    if (manifest != null && manifest.dependencies.ContainsKey(EOSPackageInfo.PackageName))
+            //    {
+            //        return true;
+            //    }
+            //}
+            //catch (Exception e)
+            //{
+            //    Debug.LogWarning($"There was a problem determining if deployed via UPM: \"{e.Message}\".");
+            //}
```
Comment (paulhazen) [inline Assets/Plugins/Source/Editor/Utility/BuildUtility.cs]: Good catch. This was working properly when we were using `Newtonsoft.Json`, because it _does_ support dictionaries.

File: Assets/Plugins/Source/Editor/Utility/BuildUtility.cs [hunk 2]
```diff
@@ -70,25 +70,39 @@ public static bool DeployedAsUPM
...
+
+            string packagePathname = Path.GetFullPath(Path.Combine("Packages", EOSPackageInfo.PackageName));
+
+            if (Directory.Exists(packagePathname))
+            {
+                Debug.Log("Deployed via UPM");
+                return true;
```
Comment (paulhazen) [inline Assets/Plugins/Source/Editor/Utility/BuildUtility.cs]: This is an insufficient test to determine whether or not the project is running as a UPM. For instance, the `manifest.json` file can define a local path or a Git URL to the package - in which case this particular test will return a false negative since the corresponding directory in `Packages` may not exist.

My suggestion would be to alter the original approach to read the `manifest.json` file line by line and check if there is a line that contains `EOSPackageInfo.PackageName`.

Only, that can't be guaranteed to work either, since the `manifest.json` file does not necessarily have entries on new-lines (the json file could all be on one line and would be valid).

So probably the best approach would be to read the contents of `manifest.json` into a string, split that string by `;`, then check each entry to see if it contains `EOSPackageInfo.PackageName`.

File: Assets/Plugins/Source/Editor/Utility/BuildUtility.cs [hunk 3]
```diff
@@ -70,25 +70,39 @@ public static bool DeployedAsUPM
...
-                if (manifest != null && manifest.dependencies.ContainsKey(EOSPackageInfo.PackageName))
-                {
-                    return true;
-                }
+            //try
+            //{
+            //    /////////////////////////////////////////////////////////
+            //    /// JsonUtility.FromJson does not support Dictionaries///
+            //    /// Causing this check to always return false         ///
+            //    /////////////////////////////////////////////////////////
```
Comment (paulhazen) [inline Assets/Plugins/Source/Editor/Utility/BuildUtility.cs]: I think as a practice we should try and have this articulation made in the body of the pull request, and the code that needs to be changed or removed should be removed instead of just commented out.

**Review by paulhazen — CHANGES_REQUESTED** [review]

File: Assets/Plugins/Source/Editor/Utility/BuildUtility.cs (hunk 2 above)
Comment (andrew-hirata-playeveryware) [reply Assets/Plugins/Source/Editor/Utility/BuildUtility.cs]: Path.GetFullPath is the Unity 'magic' way to resolve UPM based paths to absolute paths, at least according to their [documentation](https://docs.unity3d.com/Manual/upm-assets.html#GetFullPath). I'm fairly confident that it should work in this situation as well.

File: Assets/Plugins/Source/Editor/Utility/BuildUtility.cs (hunk 3 above)
Comment (andrew-hirata-playeveryware) [reply Assets/Plugins/Source/Editor/Utility/BuildUtility.cs]: I can agree with that.

**Review by andrew-hirata-playeveryware — APPROVED** [review]

File: Assets/Plugins/Source/Editor/Utility/BuildUtility.cs (hunk 2 above)
Comment (paulhazen) [reply Assets/Plugins/Source/Editor/Utility/BuildUtility.cs]: > Path.GetFullPath is the Unity 'magic' way to resolve UPM based paths to absolute paths, at least according to their [documentation](https://docs.unity3d.com/Manual/upm-assets.html#GetFullPath). I'm fairly confident that it should work in this situation as well.

Oh that's right! Dang, I keep forgetting that Unity be like that. I'll mark this conversation as resolved. My mistake.

**Review by paulhazen — APPROVED** [review]
